package server;
// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.



public final class MusicSearchImpl_Stub
    extends java.rmi.server.RemoteStub
    implements MusicSearch, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_searchForSong_0;
    
    static {
	try {
	    $method_searchForSong_0 = MusicSearch.class.getMethod("searchForSong", new java.lang.Class[] {java.lang.String.class, int.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public MusicSearchImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of searchForSong(String, int)
    public util.MusicInfo searchForSong(java.lang.String $param_String_1, int $param_int_2)
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_searchForSong_0, new java.lang.Object[] {$param_String_1, new java.lang.Integer($param_int_2)}, -6905808651986126086L);
	    return ((util.MusicInfo) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
